<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos\Context\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Context.Response.Headers</code>
 */
class Headers extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string content_type = 1[json_name = "content_type"];</code>
     */
    private $content_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $content_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Context::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string content_type = 1[json_name = "content_type"];</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>string content_type = 1[json_name = "content_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->content_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Headers::class, \Protos\Context_Response_Headers::class);

