<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/spanv2.proto

namespace Protos\Span;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Span.Context</code>
 */
class Context extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.Span.Context.DB db = 1;</code>
     */
    private $db = null;
    /**
     * Generated from protobuf field <code>.protos.Span.Context.HTTP http = 2;</code>
     */
    private $http = null;
    /**
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     */
    private $tags;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\Span\Context\DB $db
     *     @type \Protos\Span\Context\HTTP $http
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Spanv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context.DB db = 1;</code>
     * @return \Protos\Span\Context\DB
     */
    public function getDb()
    {
        return $this->db;
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context.DB db = 1;</code>
     * @param \Protos\Span\Context\DB $var
     * @return $this
     */
    public function setDb($var)
    {
        GPBUtil::checkMessage($var, \Protos\Span_Context_DB::class);
        $this->db = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context.HTTP http = 2;</code>
     * @return \Protos\Span\Context\HTTP
     */
    public function getHttp()
    {
        return $this->http;
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context.HTTP http = 2;</code>
     * @param \Protos\Span\Context\HTTP $var
     * @return $this
     */
    public function setHttp($var)
    {
        GPBUtil::checkMessage($var, \Protos\Span_Context_HTTP::class);
        $this->http = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Context::class, \Protos\Span_Context::class);

