<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace Protos\System;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.System.Kubernetes</code>
 */
class Kubernetes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     */
    private $namespace = '';
    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Pod pod = 2;</code>
     */
    private $pod = null;
    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Node node = 3;</code>
     */
    private $node = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $namespace
     *     @type \Protos\System\Kubernetes\Pod $pod
     *     @type \Protos\System\Kubernetes\Node $node
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\System::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @return string
     */
    public function getNamespace()
    {
        return $this->namespace;
    }

    /**
     * Generated from protobuf field <code>string namespace = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNamespace($var)
    {
        GPBUtil::checkString($var, True);
        $this->namespace = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Pod pod = 2;</code>
     * @return \Protos\System\Kubernetes\Pod
     */
    public function getPod()
    {
        return $this->pod;
    }

    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Pod pod = 2;</code>
     * @param \Protos\System\Kubernetes\Pod $var
     * @return $this
     */
    public function setPod($var)
    {
        GPBUtil::checkMessage($var, \Protos\System_Kubernetes_Pod::class);
        $this->pod = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Node node = 3;</code>
     * @return \Protos\System\Kubernetes\Node
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * Generated from protobuf field <code>.protos.System.Kubernetes.Node node = 3;</code>
     * @param \Protos\System\Kubernetes\Node $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkMessage($var, \Protos\System_Kubernetes_Node::class);
        $this->node = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Kubernetes::class, \Protos\System_Kubernetes::class);

