<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/metadata.proto

namespace GPBMetadata\Protos;

class Metadata
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protos\Service::initOnce();
        \GPBMetadata\Protos\Process::initOnce();
        \GPBMetadata\Protos\System::initOnce();
        \GPBMetadata\Protos\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a1570726f746f732f6d657461646174612e70726f746f12067072" .
            "6f746f731a1470726f746f732f70726f636573732e70726f746f1a137072" .
            "6f746f732f73797374656d2e70726f746f1a1170726f746f732f75736572" .
            "2e70726f746f228a010a084d6574614461746112200a0773657276696365" .
            "18012001280b320f2e70726f746f732e5365727669636512200a0770726f" .
            "6365737318022001280b320f2e70726f746f732e50726f63657373121e0a" .
            "0673797374656d18032001280b320e2e70726f746f732e53797374656d12" .
            "1a0a047573657218042001280b320c2e70726f746f732e55736572620670" .
            "726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

