<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/payload.proto

namespace GPBMetadata\Protos;

class Payload
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Protos\Metadata::initOnce();
        \GPBMetadata\Protos\Transactionv2::initOnce();
        \GPBMetadata\Protos\Spanv2::initOnce();
        \GPBMetadata\Protos\Errorv2::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a84020a1470726f746f732f7061796c6f61642e70726f746f120670726f" .
            "746f731a1a70726f746f732f7472616e73616374696f6e76322e70726f74" .
            "6f1a1370726f746f732f7370616e76322e70726f746f1a1470726f746f73" .
            "2f6572726f7276322e70726f746f2294010a075061796c6f616412220a08" .
            "6d6574616461746118012001280b32102e70726f746f732e4d6574614461" .
            "7461121b0a057370616e7318022003280b320c2e70726f746f732e537061" .
            "6e12290a0c7472616e73616374696f6e7318032003280b32132e70726f74" .
            "6f732e5472616e73616374696f6e121d0a066572726f727318042003280b" .
            "320d2e70726f746f732e4572726f72620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

