<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/process.proto

namespace GPBMetadata\Protos;

class Process
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a690a1470726f746f732f70726f636573732e70726f746f120670726f74" .
            "6f7322410a0750726f63657373120b0a03706964180120012805120c0a04" .
            "70706964180220012805120d0a057469746c65180320012809120c0a0461" .
            "726776180420032809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

