<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/stacktrace.proto

namespace GPBMetadata\Protos;

class Stacktrace
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a90030a1770726f746f732f737461636b74726163652e70726f746f1206" .
            "70726f746f7322e4020a0a537461636b5472616365121a0a086162735f70" .
            "61746818012001280952086162735f70617468120d0a05636f6c6e6f1802" .
            "2001280512220a0c636f6e746578745f6c696e65180320012809520c636f" .
            "6e746578745f6c696e6512100a0866696c656e616d651804200128091210" .
            "0a0866756e6374696f6e18052001280912240a0d6c6962726172795f6672" .
            "616d65180620012808520d6c6962726172795f6672616d65120e0a066c69" .
            "6e656e6f180720012805120e0a066d6f64756c6518082001280912220a0c" .
            "706f73745f636f6e74657874180920032809520c706f73745f636f6e7465" .
            "787412200a0b7072655f636f6e74657874180a20032809520b7072655f63" .
            "6f6e74657874122a0a0476617273180b2003280b321c2e70726f746f732e" .
            "537461636b54726163652e56617273456e7472791a2b0a0956617273456e" .
            "747279120b0a036b6579180120012809120d0a0576616c75651802200128" .
            "093a023801620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

