<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace GPBMetadata\Protos;

class System
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93030a1370726f746f732f73797374656d2e70726f746f120670726f74" .
            "6f7322eb020a0653797374656d12140a0c61726368697465637475726518" .
            "012001280912100a08686f73746e616d6518022001280912100a08706c61" .
            "74666f726d180320012809122b0a09636f6e7461696e657218042001280b" .
            "32182e70726f746f732e53797374656d2e436f6e7461696e6572122d0a0a" .
            "6b756265726e6574657318052001280b32192e70726f746f732e53797374" .
            "656d2e4b756265726e657465731a170a09436f6e7461696e6572120a0a02" .
            "69641801200128091ab1010a0a4b756265726e6574657312110a096e616d" .
            "657370616365180120012809122a0a03706f6418022001280b321d2e7072" .
            "6f746f732e53797374656d2e4b756265726e657465732e506f64122c0a04" .
            "6e6f646518032001280b321e2e70726f746f732e53797374656d2e4b7562" .
            "65726e657465732e4e6f64651a200a03506f64120c0a046e616d65180120" .
            "012809120b0a037569641802200128091a140a044e6f6465120c0a046e61" .
            "6d65180120012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

