<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user.proto

namespace GPBMetadata\Protos;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a580a1170726f746f732f757365722e70726f746f120670726f746f7322" .
            "330a0455736572120a0a026964180120012809120d0a05656d61696c1802" .
            "2001280912100a08757365726e616d65180320012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

