<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Error.Exception</code>
 */
class Exception extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    private $code = '';
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string module = 3;</code>
     */
    private $module = '';
    /**
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     */
    private $attributes;
    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     */
    private $stacktrace;
    /**
     * Generated from protobuf field <code>bool handled = 6;</code>
     */
    private $handled = false;
    /**
     * Generated from protobuf field <code>string type = 7;</code>
     */
    private $type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $code
     *     @type string $message
     *     @type string $module
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $stacktrace
     *     @type bool $handled
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Errorv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string module = 3;</code>
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * Generated from protobuf field <code>string module = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->module = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStacktrace()
    {
        return $this->stacktrace;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     * @param \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStacktrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\StackTrace::class);
        $this->stacktrace = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool handled = 6;</code>
     * @return bool
     */
    public function getHandled()
    {
        return $this->handled;
    }

    /**
     * Generated from protobuf field <code>bool handled = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setHandled($var)
    {
        GPBUtil::checkBool($var);
        $this->handled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 7;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Exception::class, \Protos\Error_Exception::class);

