<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Error.Log</code>
 */
class Log extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string level = 1;</code>
     */
    private $level = '';
    /**
     * Generated from protobuf field <code>string logger_name = 2[json_name = "logger_name"];</code>
     */
    private $logger_name = '';
    /**
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';
    /**
     * Generated from protobuf field <code>string param_message = 4[json_name = "param_message"];</code>
     */
    private $param_message = '';
    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     */
    private $stacktrace;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $level
     *     @type string $logger_name
     *     @type string $message
     *     @type string $param_message
     *     @type \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $stacktrace
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Errorv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string level = 1;</code>
     * @return string
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Generated from protobuf field <code>string level = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkString($var, True);
        $this->level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logger_name = 2[json_name = "logger_name"];</code>
     * @return string
     */
    public function getLoggerName()
    {
        return $this->logger_name;
    }

    /**
     * Generated from protobuf field <code>string logger_name = 2[json_name = "logger_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setLoggerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->logger_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string param_message = 4[json_name = "param_message"];</code>
     * @return string
     */
    public function getParamMessage()
    {
        return $this->param_message;
    }

    /**
     * Generated from protobuf field <code>string param_message = 4[json_name = "param_message"];</code>
     * @param string $var
     * @return $this
     */
    public function setParamMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->param_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStacktrace()
    {
        return $this->stacktrace;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 5;</code>
     * @param \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStacktrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\StackTrace::class);
        $this->stacktrace = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Log::class, \Protos\Error_Log::class);

