<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos\Error;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Error.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Default must be true if you have single transaction
     *
     * Generated from protobuf field <code>bool sampled = 1;</code>
     */
    private $sampled = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $sampled
     *           Default must be true if you have single transaction
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Errorv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Default must be true if you have single transaction
     *
     * Generated from protobuf field <code>bool sampled = 1;</code>
     * @return bool
     */
    public function getSampled()
    {
        return $this->sampled;
    }

    /**
     * Default must be true if you have single transaction
     *
     * Generated from protobuf field <code>bool sampled = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSampled($var)
    {
        GPBUtil::checkBool($var);
        $this->sampled = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Transaction::class, \Protos\Error_Transaction::class);

