<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos\Context\Request;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Context.Request.Url</code>
 */
class Url extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     */
    private $raw = '';
    /**
     * Generated from protobuf field <code>string protocol = 2;</code>
     */
    private $protocol = '';
    /**
     * Generated from protobuf field <code>string full = 3;</code>
     */
    private $full = '';
    /**
     * Generated from protobuf field <code>string hostname = 4;</code>
     */
    private $hostname = '';
    /**
     * Generated from protobuf field <code>string port = 5;</code>
     */
    private $port = '';
    /**
     * Generated from protobuf field <code>string pathname = 6;</code>
     */
    private $pathname = '';
    /**
     * Generated from protobuf field <code>string search = 7;</code>
     */
    private $search = '';
    /**
     * Generated from protobuf field <code>string hash = 8;</code>
     */
    private $hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $raw
     *     @type string $protocol
     *     @type string $full
     *     @type string $hostname
     *     @type string $port
     *     @type string $pathname
     *     @type string $search
     *     @type string $hash
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Context::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     * @return string
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Generated from protobuf field <code>string raw = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRaw($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string protocol = 2;</code>
     * @return string
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>string protocol = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string full = 3;</code>
     * @return string
     */
    public function getFull()
    {
        return $this->full;
    }

    /**
     * Generated from protobuf field <code>string full = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFull($var)
    {
        GPBUtil::checkString($var, True);
        $this->full = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4;</code>
     * @return string
     */
    public function getHostname()
    {
        return $this->hostname;
    }

    /**
     * Generated from protobuf field <code>string hostname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHostname($var)
    {
        GPBUtil::checkString($var, True);
        $this->hostname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string port = 5;</code>
     * @return string
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>string port = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkString($var, True);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string pathname = 6;</code>
     * @return string
     */
    public function getPathname()
    {
        return $this->pathname;
    }

    /**
     * Generated from protobuf field <code>string pathname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPathname($var)
    {
        GPBUtil::checkString($var, True);
        $this->pathname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string search = 7;</code>
     * @return string
     */
    public function getSearch()
    {
        return $this->search;
    }

    /**
     * Generated from protobuf field <code>string search = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSearch($var)
    {
        GPBUtil::checkString($var, True);
        $this->search = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hash = 8;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>string hash = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, True);
        $this->hash = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Url::class, \Protos\Context_Request_Url::class);

