<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Request\Url instead.
     * @deprecated
     */
    class Context_Request_Url {}
}
class_exists(Context\Request\Url::class);
@trigger_error('Protos\Context_Request_Url is deprecated and will be removed in the next major release. Use Protos\Context\Request\Url instead', E_USER_DEPRECATED);

