<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Request instead.
     * @deprecated
     */
    class Context_Request {}
}
class_exists(Context\Request::class);
@trigger_error('Protos\Context_Request is deprecated and will be removed in the next major release. Use Protos\Context\Request instead', E_USER_DEPRECATED);

