<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Response\Headers instead.
     * @deprecated
     */
    class Context_Response_Headers {}
}
class_exists(Context\Response\Headers::class);
@trigger_error('Protos\Context_Response_Headers is deprecated and will be removed in the next major release. Use Protos\Context\Response\Headers instead', E_USER_DEPRECATED);

