<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Response instead.
     * @deprecated
     */
    class Context_Response {}
}
class_exists(Context\Response::class);
@trigger_error('Protos\Context_Response is deprecated and will be removed in the next major release. Use Protos\Context\Response instead', E_USER_DEPRECATED);

