<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Request\Headers instead.
     * @deprecated
     */
    class Context_Request_Headers {}
}
class_exists(Context\Request\Headers::class);
@trigger_error('Protos\Context_Request_Headers is deprecated and will be removed in the next major release. Use Protos\Context\Request\Headers instead', E_USER_DEPRECATED);

