<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Context</code>
 */
class Context extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> custom = 1;</code>
     */
    private $custom;
    /**
     * Generated from protobuf field <code>.protos.Context.Response response = 2;</code>
     */
    private $response = null;
    /**
     * Generated from protobuf field <code>.protos.Context.Request request = 3;</code>
     */
    private $request = null;
    /**
     * Generated from protobuf field <code>map<string, string> tags = 4;</code>
     */
    private $tags;
    /**
     * Generated from protobuf field <code>.protos.User user = 5;</code>
     */
    private $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $custom
     *     @type \Protos\Context\Response $response
     *     @type \Protos\Context\Request $request
     *     @type array|\Google\Protobuf\Internal\MapField $tags
     *     @type \Protos\User $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Context::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> custom = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCustom()
    {
        return $this->custom;
    }

    /**
     * Generated from protobuf field <code>map<string, string> custom = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCustom($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->custom = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Response response = 2;</code>
     * @return \Protos\Context\Response
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Response response = 2;</code>
     * @param \Protos\Context\Response $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Response::class);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request request = 3;</code>
     * @return \Protos\Context\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request request = 3;</code>
     * @param \Protos\Context\Request $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Request::class);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Generated from protobuf field <code>map<string, string> tags = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTags($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->tags = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.User user = 5;</code>
     * @return \Protos\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.protos.User user = 5;</code>
     * @param \Protos\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Protos\User::class);
        $this->user = $var;

        return $this;
    }

}

