<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Context\Request\Socket instead.
     * @deprecated
     */
    class Context_Request_Socket {}
}
class_exists(Context\Request\Socket::class);
@trigger_error('Protos\Context_Request_Socket is deprecated and will be removed in the next major release. Use Protos\Context\Request\Socket instead', E_USER_DEPRECATED);

