<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Error</code>
 */
class Error extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    private $timestamp = 0;
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     */
    private $transaction_id = '';
    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     */
    private $trace_id = '';
    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     */
    private $parent_id = '';
    /**
     * Generated from protobuf field <code>.protos.Error.Transaction transaction = 6;</code>
     */
    private $transaction = null;
    /**
     * Generated from protobuf field <code>.protos.Context context = 7;</code>
     */
    private $context = null;
    /**
     * Generated from protobuf field <code>string culprit = 8;</code>
     */
    private $culprit = '';
    /**
     * Generated from protobuf field <code>.protos.Error.Exception exception = 9;</code>
     */
    private $exception = null;
    /**
     * Generated from protobuf field <code>.protos.Error.Log log = 10;</code>
     */
    private $log = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type string $id
     *     @type string $transaction_id
     *     @type string $trace_id
     *     @type string $parent_id
     *     @type \Protos\Error\Transaction $transaction
     *     @type \Protos\Context $context
     *     @type string $culprit
     *     @type \Protos\Error\Exception $exception
     *     @type \Protos\Error\Log $log
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Errorv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Transaction transaction = 6;</code>
     * @return \Protos\Error\Transaction
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Transaction transaction = 6;</code>
     * @param \Protos\Error\Transaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Protos\Error_Transaction::class);
        $this->transaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context context = 7;</code>
     * @return \Protos\Context
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.protos.Context context = 7;</code>
     * @param \Protos\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string culprit = 8;</code>
     * @return string
     */
    public function getCulprit()
    {
        return $this->culprit;
    }

    /**
     * Generated from protobuf field <code>string culprit = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCulprit($var)
    {
        GPBUtil::checkString($var, True);
        $this->culprit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Exception exception = 9;</code>
     * @return \Protos\Error\Exception
     */
    public function getException()
    {
        return $this->exception;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Exception exception = 9;</code>
     * @param \Protos\Error\Exception $var
     * @return $this
     */
    public function setException($var)
    {
        GPBUtil::checkMessage($var, \Protos\Error_Exception::class);
        $this->exception = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Log log = 10;</code>
     * @return \Protos\Error\Log
     */
    public function getLog()
    {
        return $this->log;
    }

    /**
     * Generated from protobuf field <code>.protos.Error.Log log = 10;</code>
     * @param \Protos\Error\Log $var
     * @return $this
     */
    public function setLog($var)
    {
        GPBUtil::checkMessage($var, \Protos\Error_Log::class);
        $this->log = $var;

        return $this;
    }

}

