<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Error\Exception instead.
     * @deprecated
     */
    class Error_Exception {}
}
class_exists(Error\Exception::class);
@trigger_error('Protos\Error_Exception is deprecated and will be removed in the next major release. Use Protos\Error\Exception instead', E_USER_DEPRECATED);

