<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/errorv2.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Error\Log instead.
     * @deprecated
     */
    class Error_Log {}
}
class_exists(Error\Log::class);
@trigger_error('Protos\Error_Log is deprecated and will be removed in the next major release. Use Protos\Error\Log instead', E_USER_DEPRECATED);

