<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/metadata.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.MetaData</code>
 */
class MetaData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.Service service = 1;</code>
     */
    private $service = null;
    /**
     * Generated from protobuf field <code>.protos.Process process = 2;</code>
     */
    private $process = null;
    /**
     * Generated from protobuf field <code>.protos.System system = 3;</code>
     */
    private $system = null;
    /**
     * Generated from protobuf field <code>.protos.User user = 4;</code>
     */
    private $user = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\Service $service
     *     @type \Protos\Process $process
     *     @type \Protos\System $system
     *     @type \Protos\User $user
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Metadata::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Service service = 1;</code>
     * @return \Protos\Service
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>.protos.Service service = 1;</code>
     * @param \Protos\Service $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkMessage($var, \Protos\Service::class);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Process process = 2;</code>
     * @return \Protos\Process
     */
    public function getProcess()
    {
        return $this->process;
    }

    /**
     * Generated from protobuf field <code>.protos.Process process = 2;</code>
     * @param \Protos\Process $var
     * @return $this
     */
    public function setProcess($var)
    {
        GPBUtil::checkMessage($var, \Protos\Process::class);
        $this->process = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.System system = 3;</code>
     * @return \Protos\System
     */
    public function getSystem()
    {
        return $this->system;
    }

    /**
     * Generated from protobuf field <code>.protos.System system = 3;</code>
     * @param \Protos\System $var
     * @return $this
     */
    public function setSystem($var)
    {
        GPBUtil::checkMessage($var, \Protos\System::class);
        $this->system = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.User user = 4;</code>
     * @return \Protos\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>.protos.User user = 4;</code>
     * @param \Protos\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \Protos\User::class);
        $this->user = $var;

        return $this;
    }

}

