<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/payload.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.MetaData metadata = 1;</code>
     */
    private $metadata = null;
    /**
     * Generated from protobuf field <code>repeated .protos.Span spans = 2;</code>
     */
    private $spans;
    /**
     * Generated from protobuf field <code>repeated .protos.Transaction transactions = 3;</code>
     */
    private $transactions;
    /**
     * Generated from protobuf field <code>repeated .protos.Error errors = 4;</code>
     */
    private $errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\MetaData $metadata
     *     @type \Protos\Span[]|\Google\Protobuf\Internal\RepeatedField $spans
     *     @type \Protos\Transaction[]|\Google\Protobuf\Internal\RepeatedField $transactions
     *     @type \Protos\Error[]|\Google\Protobuf\Internal\RepeatedField $errors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Payload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.MetaData metadata = 1;</code>
     * @return \Protos\MetaData
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>.protos.MetaData metadata = 1;</code>
     * @param \Protos\MetaData $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Protos\MetaData::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Span spans = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSpans()
    {
        return $this->spans;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Span spans = 2;</code>
     * @param \Protos\Span[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSpans($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Span::class);
        $this->spans = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Transaction transactions = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransactions()
    {
        return $this->transactions;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Transaction transactions = 3;</code>
     * @param \Protos\Transaction[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransactions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Transaction::class);
        $this->transactions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Error errors = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.Error errors = 4;</code>
     * @param \Protos\Error[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\Error::class);
        $this->errors = $arr;

        return $this;
    }

}

