<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/process.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Process</code>
 */
class Process extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 pid = 1;</code>
     */
    private $pid = 0;
    /**
     * Generated from protobuf field <code>int32 ppid = 2;</code>
     */
    private $ppid = 0;
    /**
     * Generated from protobuf field <code>string title = 3;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>repeated string argv = 4;</code>
     */
    private $argv;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pid
     *     @type int $ppid
     *     @type string $title
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $argv
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Process::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 pid = 1;</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Generated from protobuf field <code>int32 pid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkInt32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ppid = 2;</code>
     * @return int
     */
    public function getPpid()
    {
        return $this->ppid;
    }

    /**
     * Generated from protobuf field <code>int32 ppid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPpid($var)
    {
        GPBUtil::checkInt32($var);
        $this->ppid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string argv = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getArgv()
    {
        return $this->argv;
    }

    /**
     * Generated from protobuf field <code>repeated string argv = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setArgv($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->argv = $arr;

        return $this;
    }

}

