<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/service.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Service\Agent instead.
     * @deprecated
     */
    class Service_Agent {}
}
class_exists(Service\Agent::class);
@trigger_error('Protos\Service_Agent is deprecated and will be removed in the next major release. Use Protos\Service\Agent instead', E_USER_DEPRECATED);

