<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/service.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Service\Framework instead.
     * @deprecated
     */
    class Service_Framework {}
}
class_exists(Service\Framework::class);
@trigger_error('Protos\Service_Framework is deprecated and will be removed in the next major release. Use Protos\Service\Framework instead', E_USER_DEPRECATED);

