<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/service.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Service\Runtime instead.
     * @deprecated
     */
    class Service_Runtime {}
}
class_exists(Service\Runtime::class);
@trigger_error('Protos\Service_Runtime is deprecated and will be removed in the next major release. Use Protos\Service\Runtime instead', E_USER_DEPRECATED);

