<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/service.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Service\Language instead.
     * @deprecated
     */
    class Service_Language {}
}
class_exists(Service\Language::class);
@trigger_error('Protos\Service_Language is deprecated and will be removed in the next major release. Use Protos\Service\Language instead', E_USER_DEPRECATED);

