<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/service.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Service</code>
 */
class Service extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protos.Service.Agent agent = 1;</code>
     */
    private $agent = null;
    /**
     * Generated from protobuf field <code>.protos.Service.Framework framework = 2;</code>
     */
    private $framework = null;
    /**
     * Generated from protobuf field <code>.protos.Service.Language language = 3;</code>
     */
    private $language = null;
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string environment = 5;</code>
     */
    private $environment = '';
    /**
     * Generated from protobuf field <code>.protos.Service.Runtime runtime = 6;</code>
     */
    private $runtime = null;
    /**
     * Generated from protobuf field <code>string version = 7;</code>
     */
    private $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protos\Service\Agent $agent
     *     @type \Protos\Service\Framework $framework
     *     @type \Protos\Service\Language $language
     *     @type string $name
     *     @type string $environment
     *     @type \Protos\Service\Runtime $runtime
     *     @type string $version
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Agent agent = 1;</code>
     * @return \Protos\Service\Agent
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Agent agent = 1;</code>
     * @param \Protos\Service\Agent $var
     * @return $this
     */
    public function setAgent($var)
    {
        GPBUtil::checkMessage($var, \Protos\Service_Agent::class);
        $this->agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Framework framework = 2;</code>
     * @return \Protos\Service\Framework
     */
    public function getFramework()
    {
        return $this->framework;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Framework framework = 2;</code>
     * @param \Protos\Service\Framework $var
     * @return $this
     */
    public function setFramework($var)
    {
        GPBUtil::checkMessage($var, \Protos\Service_Framework::class);
        $this->framework = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Language language = 3;</code>
     * @return \Protos\Service\Language
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Language language = 3;</code>
     * @param \Protos\Service\Language $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkMessage($var, \Protos\Service_Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string environment = 5;</code>
     * @return string
     */
    public function getEnvironment()
    {
        return $this->environment;
    }

    /**
     * Generated from protobuf field <code>string environment = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEnvironment($var)
    {
        GPBUtil::checkString($var, True);
        $this->environment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Runtime runtime = 6;</code>
     * @return \Protos\Service\Runtime
     */
    public function getRuntime()
    {
        return $this->runtime;
    }

    /**
     * Generated from protobuf field <code>.protos.Service.Runtime runtime = 6;</code>
     * @param \Protos\Service\Runtime $var
     * @return $this
     */
    public function setRuntime($var)
    {
        GPBUtil::checkMessage($var, \Protos\Service_Runtime::class);
        $this->runtime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string version = 7;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>string version = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

