<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/spanv2.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Span</code>
 */
class Span extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     */
    private $timestamp = 0;
    /**
     * Generated from protobuf field <code>string id = 2;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     */
    private $transaction_id = '';
    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     */
    private $trace_id = '';
    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     */
    private $parent_id = '';
    /**
     * in ms
     *
     * Generated from protobuf field <code>float start = 6;</code>
     */
    private $start = 0.0;
    /**
     * Generated from protobuf field <code>string subtype = 7;</code>
     */
    private $subtype = '';
    /**
     * Generated from protobuf field <code>string action = 8;</code>
     */
    private $action = '';
    /**
     * Generated from protobuf field <code>.protos.Span.Context context = 9;</code>
     */
    private $context = null;
    /**
     * Generated from protobuf field <code>float duration = 10;</code>
     */
    private $duration = 0.0;
    /**
     * Generated from protobuf field <code>string name = 11;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 12;</code>
     */
    private $stacktrace;
    /**
     * Generated from protobuf field <code>string type = 13;</code>
     */
    private $type = '';
    /**
     * is sync or async
     *
     * Generated from protobuf field <code>bool sync = 14;</code>
     */
    private $sync = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $timestamp
     *     @type string $id
     *     @type string $transaction_id
     *     @type string $trace_id
     *     @type string $parent_id
     *     @type float $start
     *           in ms
     *     @type string $subtype
     *     @type string $action
     *     @type \Protos\Span\Context $context
     *     @type float $duration
     *     @type string $name
     *     @type \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $stacktrace
     *     @type string $type
     *     @type bool $sync
     *           is sync or async
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Spanv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>string transaction_id = 3[json_name = "transaction_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 4[json_name = "trace_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 5[json_name = "parent_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * in ms
     *
     * Generated from protobuf field <code>float start = 6;</code>
     * @return float
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * in ms
     *
     * Generated from protobuf field <code>float start = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkFloat($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtype = 7;</code>
     * @return string
     */
    public function getSubtype()
    {
        return $this->subtype;
    }

    /**
     * Generated from protobuf field <code>string subtype = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtype($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtype = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action = 8;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * Generated from protobuf field <code>string action = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context context = 9;</code>
     * @return \Protos\Span\Context
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.protos.Span.Context context = 9;</code>
     * @param \Protos\Span\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Protos\Span_Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float duration = 10;</code>
     * @return float
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>float duration = 10;</code>
     * @param float $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 11;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStacktrace()
    {
        return $this->stacktrace;
    }

    /**
     * Generated from protobuf field <code>repeated .protos.StackTrace stacktrace = 12;</code>
     * @param \Protos\StackTrace[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStacktrace($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protos\StackTrace::class);
        $this->stacktrace = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 13;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * is sync or async
     *
     * Generated from protobuf field <code>bool sync = 14;</code>
     * @return bool
     */
    public function getSync()
    {
        return $this->sync;
    }

    /**
     * is sync or async
     *
     * Generated from protobuf field <code>bool sync = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setSync($var)
    {
        GPBUtil::checkBool($var);
        $this->sync = $var;

        return $this;
    }

}

