<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/spanv2.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Span\Context\DB instead.
     * @deprecated
     */
    class Span_Context_DB {}
}
class_exists(Span\Context\DB::class);
@trigger_error('Protos\Span_Context_DB is deprecated and will be removed in the next major release. Use Protos\Span\Context\DB instead', E_USER_DEPRECATED);

