<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\System\Kubernetes\Node instead.
     * @deprecated
     */
    class System_Kubernetes_Node {}
}
class_exists(System\Kubernetes\Node::class);
@trigger_error('Protos\System_Kubernetes_Node is deprecated and will be removed in the next major release. Use Protos\System\Kubernetes\Node instead', E_USER_DEPRECATED);

