<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\System\Kubernetes\Pod instead.
     * @deprecated
     */
    class System_Kubernetes_Pod {}
}
class_exists(System\Kubernetes\Pod::class);
@trigger_error('Protos\System_Kubernetes_Pod is deprecated and will be removed in the next major release. Use Protos\System\Kubernetes\Pod instead', E_USER_DEPRECATED);

