<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\System\Kubernetes instead.
     * @deprecated
     */
    class System_Kubernetes {}
}
class_exists(System\Kubernetes::class);
@trigger_error('Protos\System_Kubernetes is deprecated and will be removed in the next major release. Use Protos\System\Kubernetes instead', E_USER_DEPRECATED);

