<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/system.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\System\Container instead.
     * @deprecated
     */
    class System_Container {}
}
class_exists(System\Container::class);
@trigger_error('Protos\System_Container is deprecated and will be removed in the next major release. Use Protos\System\Container instead', E_USER_DEPRECATED);

