<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transactionv2.proto

namespace Protos;

if (false) {
    /**
     * This class is deprecated. Use Protos\Transaction\SpanCount instead.
     * @deprecated
     */
    class Transaction_SpanCount {}
}
class_exists(Transaction\SpanCount::class);
@trigger_error('Protos\Transaction_SpanCount is deprecated and will be removed in the next major release. Use Protos\Transaction\SpanCount instead', E_USER_DEPRECATED);

