<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transactionv2.proto

namespace Protos;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string trace_id = 2[json_name = "trace_id"];</code>
     */
    private $trace_id = '';
    /**
     * Generated from protobuf field <code>string parent_id = 3[json_name = "parent_id"];</code>
     */
    private $parent_id = '';
    /**
     * Generated from protobuf field <code>string name = 4;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string type = 5;</code>
     */
    private $type = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     */
    private $timestamp = 0;
    /**
     * in ms with 3 decimal points
     *
     * Generated from protobuf field <code>float duration = 7;</code>
     */
    private $duration = 0.0;
    /**
     * Generated from protobuf field <code>string result = 8;</code>
     */
    private $result = '';
    /**
     * Generated from protobuf field <code>bool sampled = 9;</code>
     */
    private $sampled = false;
    /**
     * Generated from protobuf field <code>map<string, string> marks = 10;</code>
     */
    private $marks;
    /**
     * Generated from protobuf field <code>.protos.Transaction.SpanCount span_count = 11[json_name = "span_count"];</code>
     */
    private $span_count = null;
    /**
     * Generated from protobuf field <code>.protos.Context context = 12;</code>
     */
    private $context = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $trace_id
     *     @type string $parent_id
     *     @type string $name
     *     @type string $type
     *     @type int|string $timestamp
     *     @type float $duration
     *           in ms with 3 decimal points
     *     @type string $result
     *     @type bool $sampled
     *     @type array|\Google\Protobuf\Internal\MapField $marks
     *     @type \Protos\Transaction\SpanCount $span_count
     *     @type \Protos\Context $context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Transactionv2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 2[json_name = "trace_id"];</code>
     * @return string
     */
    public function getTraceId()
    {
        return $this->trace_id;
    }

    /**
     * Generated from protobuf field <code>string trace_id = 2[json_name = "trace_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setTraceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->trace_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 3[json_name = "parent_id"];</code>
     * @return string
     */
    public function getParentId()
    {
        return $this->parent_id;
    }

    /**
     * Generated from protobuf field <code>string parent_id = 3[json_name = "parent_id"];</code>
     * @param string $var
     * @return $this
     */
    public function setParentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string type = 5;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * in ms with 3 decimal points
     *
     * Generated from protobuf field <code>float duration = 7;</code>
     * @return float
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * in ms with 3 decimal points
     *
     * Generated from protobuf field <code>float duration = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string result = 8;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool sampled = 9;</code>
     * @return bool
     */
    public function getSampled()
    {
        return $this->sampled;
    }

    /**
     * Generated from protobuf field <code>bool sampled = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setSampled($var)
    {
        GPBUtil::checkBool($var);
        $this->sampled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> marks = 10;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMarks()
    {
        return $this->marks;
    }

    /**
     * Generated from protobuf field <code>map<string, string> marks = 10;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMarks($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->marks = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Transaction.SpanCount span_count = 11[json_name = "span_count"];</code>
     * @return \Protos\Transaction\SpanCount
     */
    public function getSpanCount()
    {
        return $this->span_count;
    }

    /**
     * Generated from protobuf field <code>.protos.Transaction.SpanCount span_count = 11[json_name = "span_count"];</code>
     * @param \Protos\Transaction\SpanCount $var
     * @return $this
     */
    public function setSpanCount($var)
    {
        GPBUtil::checkMessage($var, \Protos\Transaction_SpanCount::class);
        $this->span_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context context = 12;</code>
     * @return \Protos\Context
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.protos.Context context = 12;</code>
     * @param \Protos\Context $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context::class);
        $this->context = $var;

        return $this;
    }

}

