<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos\Context;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Context.Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string body = 1;</code>
     */
    private $body = '';
    /**
     * Generated from protobuf field <code>map<string, string> env = 2;</code>
     */
    private $env;
    /**
     * Generated from protobuf field <code>.protos.Context.Request.Headers headers = 3;</code>
     */
    private $headers = null;
    /**
     * Generated from protobuf field <code>string http_version = 4[json_name = "http_version"];</code>
     */
    private $http_version = '';
    /**
     * Generated from protobuf field <code>string method = 5;</code>
     */
    private $method = '';
    /**
     * Generated from protobuf field <code>.protos.Context.Request.Socket socket = 6;</code>
     */
    private $socket = null;
    /**
     * Generated from protobuf field <code>.protos.Context.Request.Url url = 7;</code>
     */
    private $url = null;
    /**
     * Generated from protobuf field <code>map<string, string> cookies = 8;</code>
     */
    private $cookies;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $body
     *     @type array|\Google\Protobuf\Internal\MapField $env
     *     @type \Protos\Context\Request\Headers $headers
     *     @type string $http_version
     *     @type string $method
     *     @type \Protos\Context\Request\Socket $socket
     *     @type \Protos\Context\Request\Url $url
     *     @type array|\Google\Protobuf\Internal\MapField $cookies
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Context::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string body = 1;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> env = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEnv()
    {
        return $this->env;
    }

    /**
     * Generated from protobuf field <code>map<string, string> env = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEnv($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->env = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Headers headers = 3;</code>
     * @return \Protos\Context\Request\Headers
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Headers headers = 3;</code>
     * @param \Protos\Context\Request\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Request_Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string http_version = 4[json_name = "http_version"];</code>
     * @return string
     */
    public function getHttpVersion()
    {
        return $this->http_version;
    }

    /**
     * Generated from protobuf field <code>string http_version = 4[json_name = "http_version"];</code>
     * @param string $var
     * @return $this
     */
    public function setHttpVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->http_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Socket socket = 6;</code>
     * @return \Protos\Context\Request\Socket
     */
    public function getSocket()
    {
        return $this->socket;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Socket socket = 6;</code>
     * @param \Protos\Context\Request\Socket $var
     * @return $this
     */
    public function setSocket($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Request_Socket::class);
        $this->socket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Url url = 7;</code>
     * @return \Protos\Context\Request\Url
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Request.Url url = 7;</code>
     * @param \Protos\Context\Request\Url $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Request_Url::class);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookies = 8;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCookies()
    {
        return $this->cookies;
    }

    /**
     * Generated from protobuf field <code>map<string, string> cookies = 8;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCookies($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->cookies = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Request::class, \Protos\Context_Request::class);

