<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto

namespace Protos\Context;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>protos.Context.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool finished = 1;</code>
     */
    private $finished = false;
    /**
     * Generated from protobuf field <code>.protos.Context.Response.Headers headers = 2;</code>
     */
    private $headers = null;
    /**
     * Generated from protobuf field <code>bool headers_sent = 3[json_name = "headers_sent"];</code>
     */
    private $headers_sent = false;
    /**
     * Generated from protobuf field <code>int32 status_code = 4[json_name = "status_code"];</code>
     */
    private $status_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $finished
     *     @type \Protos\Context\Response\Headers $headers
     *     @type bool $headers_sent
     *     @type int $status_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Context::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool finished = 1;</code>
     * @return bool
     */
    public function getFinished()
    {
        return $this->finished;
    }

    /**
     * Generated from protobuf field <code>bool finished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->finished = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Response.Headers headers = 2;</code>
     * @return \Protos\Context\Response\Headers
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>.protos.Context.Response.Headers headers = 2;</code>
     * @param \Protos\Context\Response\Headers $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkMessage($var, \Protos\Context_Response_Headers::class);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool headers_sent = 3[json_name = "headers_sent"];</code>
     * @return bool
     */
    public function getHeadersSent()
    {
        return $this->headers_sent;
    }

    /**
     * Generated from protobuf field <code>bool headers_sent = 3[json_name = "headers_sent"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHeadersSent($var)
    {
        GPBUtil::checkBool($var);
        $this->headers_sent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 status_code = 4[json_name = "status_code"];</code>
     * @return int
     */
    public function getStatusCode()
    {
        return $this->status_code;
    }

    /**
     * Generated from protobuf field <code>int32 status_code = 4[json_name = "status_code"];</code>
     * @param int $var
     * @return $this
     */
    public function setStatusCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->status_code = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Response::class, \Protos\Context_Response::class);

